import { Menu } from './menu';

export class Countries {
    public countries = [
        new Menu('United States', 'US'),
        /*new Menu('Albania', 'AL'),
        new Menu('Algeria', 'DZ'),
        new Menu('American Samoa', 'AS'),
        new Menu('Andorra', 'AD'),
        new Menu('Angola', 'AO'),
        new Menu('Anguilla', 'AI'),
        new Menu('Antigua And Barbuda', 'AG'),
        new Menu('Argentina', 'AR'),
        new Menu('Armenia', 'AM'),
        new Menu('Aruba', 'AW'),
        new Menu('Australia', 'AU'),
        new Menu('Austria', 'AT'),
        new Menu('Azerbaijan', 'AZ'),
        new Menu('Bahamas', 'BS'),
        new Menu('Bahrain', 'BH'),
        new Menu('Bangladesh', 'BD'),
        new Menu('Barbados', 'BB'),
        new Menu('Belarus', 'BY'),
        new Menu('Belgium', 'BE'),
        new Menu('Belize', 'BZ'),
        new Menu('Benin', 'BJ'),
        new Menu('Bermuda', 'BM'),
        new Menu('Bhutan', 'BT'),
        new Menu('Bolivia', 'BO'),
        new Menu('Botswana', 'BW'),
        new Menu('Brazil', 'BR'),
        new Menu('Brunei Darussalam', 'BN'),
        new Menu('Bulgaria', 'BG'),
        new Menu('Burkina Faso', 'BF'),
        new Menu('Burundi', 'BI'),
        new Menu('Cambodia', 'KH'),
        new Menu('Cameroon', 'CM'),
        new Menu('Canada', 'CA'),
        new Menu('Cape Verde', 'CV'),
        new Menu('Cayman Islands', 'KY'),
        new Menu('Central African Republic', 'CF'),
        new Menu('Chad', 'TD'),
        new Menu('Chile', 'CL'),
        new Menu('China', 'CN'),
        new Menu('Colombia', 'CO'),
        new Menu('Congo, The Democratic Republic Of The', 'CD'),
        new Menu('Congo', 'CG'),
        new Menu('Cook Islands', 'CK'),
        new Menu('Costa Rica', 'CR'),
        new Menu('Croatia', 'HR'),
        new Menu('Cyprus', 'CY'),
        new Menu('Czech Republic', 'CZ'),
        new Menu('Yemen', 'YE'),
        new Menu('Denmark', 'DK'),
        new Menu('Djibouti', 'DJ'),
        new Menu('Dominica', 'DM'),
        new Menu('Dominican Republic', 'DO'),
        new Menu('Ecuador', 'EC'),
        new Menu('Egypt', 'EG'),
        new Menu('El Salvador', 'SV'),
        new Menu('Equatorial Guinea', 'GQ'),
        new Menu('Eritrea', 'ER'),
        new Menu('Estonia', 'EE'),
        new Menu('Ethiopia', 'ET'),
        new Menu('Faroe Islands', 'FO'),
        new Menu('Fiji', 'FJ'),
        new Menu('Finland', 'FI'),
        new Menu('France', 'FR'),
        new Menu('French Guiana', 'GF'),
        new Menu('French Polynesia', 'PF'),
        new Menu('Gabon', 'GA'),
        new Menu('Gambia', 'GM'),
        new Menu('Georgia', 'GE'),
        new Menu('Germany', 'DE'),
        new Menu('Ghana', 'GH'),
        new Menu('Gibraltar', 'GI'),
        new Menu('Greece', 'GR'),
        new Menu('Greenland', 'GL'),
        new Menu('Grenada', 'GD'),
        new Menu('Guadeloupe', 'GP'),
        new Menu('Guam', 'GU'),
        new Menu('Guatemala', 'GT'),
        new Menu('Guinea', 'GN'),
        new Menu('Guinea-Bissau', 'GW'),
        new Menu('Guyana', 'GY'),
        new Menu('Haiti', 'HT'),
        new Menu('Honduras', 'HN'),
        new Menu('Hong Kong', 'HK'),
        new Menu('Hungary', 'HU'),
        new Menu('Iceland', 'IS'),
        new Menu('India', 'IN'),
        new Menu('Indonesia', 'ID'),
        new Menu('Ireland', 'IE'),
        new Menu('Israel', 'IL'),
        new Menu('Italy', 'IT'),
        new Menu('Jamaica', 'JM'),
        new Menu('Japan', 'JP'),
        new Menu('Jordan', 'JO'),
        new Menu('Kazakhstan', 'KZ'),
        new Menu('Kenya', 'KE'),
        new Menu('Korea, Republic Of', 'KR'),
        new Menu('Kuwait', 'KW'),
        new Menu('Kyrgyzstan', 'KG'),
        new Menu('Lao Peoples Democratic Republic', 'LA'),
        new Menu('Latvia', 'LV'),
        new Menu('Lebanon', 'LB'),
        new Menu('Lesotho', 'LS'),
        new Menu('Liechtenstein', 'LI'),
        new Menu('Lithuania', 'LT'),
        new Menu('Luxembourg', 'LU'),
        new Menu('Macao', 'MO'),
        new Menu('Macedonia, The Former Yugoslav Republic Of', 'MK'),
        new Menu('Madagascar', 'MG'),
        new Menu('Malawi', 'MW'),
        new Menu('Malaysia', 'MY'),
        new Menu('Maldives', 'MV'),
        new Menu('Mali', 'ML'),
        new Menu('Malta', 'MT'),
        new Menu('Marshall Islands', 'MH'),
        new Menu('Martinique', 'MQ'),
        new Menu('Mauritania', 'MR'),
        new Menu('Mauritius', 'MU'),
        new Menu('Mexico', 'MX'),
        new Menu('Micronesia, Federated States Of', 'FM'),
        new Menu('Moldova', 'MD'),
        new Menu('Monaco', 'MC'),
        new Menu('Mongolia', 'MN'),
        new Menu('Montserrat', 'MS'),
        new Menu('Morocco', 'MA'),
        new Menu('Mozambique', 'MZ'),
        new Menu('Namibia', 'NA'),
        new Menu('Nepal', 'NP'),
        new Menu('Netherlands', 'NL'),
        new Menu('Netherlands Antilles', 'AN'),
        new Menu('New Caledonia', 'NC'),
        new Menu('New Zealand', 'NZ'),
        new Menu('Nicaragua', 'NI'),
        new Menu('Niger', 'NE'),
        new Menu('Nigeria', 'NG'),
        new Menu('Norway', 'NO'),
        new Menu('Oman', 'OM'),
        new Menu('Pakistan', 'PK'),
        new Menu('Palau', 'PW'),
        new Menu('Panama', 'PA'),
        new Menu('Papua New Guinea', 'PG'),
        new Menu('Paraguay', 'PY'),
        new Menu('Peru', 'PE'),
        new Menu('Philippines', 'PH'),
        new Menu('Poland', 'PL'),
        new Menu('Portugal', 'PT'),
        new Menu('Puerto Rico', 'PR'),
        new Menu('Qatar', 'QA'),
        new Menu('Reunion', 'RE'),
        new Menu('Romania', 'RO'),
        new Menu('Russian Federation', 'RU'),
        new Menu('Rwanda', 'RW'),
        new Menu('San Marino', 'SM'),
        new Menu('Saudi Arabia', 'SA'),
        new Menu('Senegal', 'SN'),
        new Menu('Seychelles', 'SC'),
        new Menu('Sierra Leone', 'SL'),
        new Menu('Singapore', 'SG'),
        new Menu('Slovakia', 'SK'),
        new Menu('Slovenia', 'SI'),
        new Menu('Somalia', 'SO'),
        new Menu('South Africa', 'ZA'),
        new Menu('Spain', 'ES'),
        new Menu('Sri Lanka', 'LK'),
        new Menu('St. Kitts And Nevis', 'NULL'),
        new Menu('St. Lucia', 'NULL'),
        new Menu('St. Vincent', 'NULL'),
        new Menu('Suriname', 'SR'),
        new Menu('Swaziland', 'NULL'),
        new Menu('Sweden', 'SE'),
        new Menu('Switzerland', 'CH'),
        new Menu('Syrian Arab Republic', 'SY'),
        new Menu('Taiwan', 'TW'),
        new Menu('Tanzania', 'TZ'),
        new Menu('Thailand', 'TH'),
        new Menu('Togo', 'TG'),
        new Menu('Trinidad And Tobago', 'TT'),
        new Menu('Tunisia', 'TN'),
        new Menu('Turkey', 'TR'),
        new Menu('Turkmenistan', 'TM'),
        new Menu('Turks And Caicos Islands', 'TC'),
        new Menu('Uganda', 'UG'),
        new Menu('Ukraine', 'UA'),
        new Menu('United Arab Emirates', 'AE'),
        new Menu('United Kingdom', 'GB'),
        new Menu('Uruguay', 'UY'),
        new Menu('Uzbekistan', 'UZ'),
        new Menu('Vanuatu', 'VU'),
        new Menu('Vatican City', 'NULL'),
        new Menu('Venezuela', 'VE'),
        new Menu('Vietnam', 'VN'),
        new Menu('Virgin Islands, U.S.', 'VI'),
        new Menu('Virgin Islands, U.S.', 'VI'),
        new Menu('Wallis And Futuna', 'WF'),
        new Menu('Zambia', 'ZM'),
        new Menu('Zimbabwe', 'ZW'),
        new Menu('Ireland, Northern', 'IE'),
        new Menu('Afghanistan', 'AF'),
        new Menu('Aland Islands', 'AX'),
        new Menu('Antarctica', 'AQ'),
        new Menu('Bosnia And Herzegovina', 'BA'),
        new Menu('Bouvet Island', 'BV'),
        new Menu('British Indian Ocean Territory', 'IO'),
        new Menu('Christmas Island', 'CX'),
        new Menu('Cocos (Keeling) Islands', 'CC'),
        new Menu('Comoros', 'KM'),
        new Menu('Cote DIvoire', 'CI'),
        new Menu('Cuba', 'CU'),
        new Menu('Falkland Islands (Malvinas)', 'FK'),
        new Menu('French Southern Territories', 'TF'),
        new Menu('Guernsey', 'GG'),
        new Menu('Heard Island And McDonald Islands', 'HM'),
        new Menu('Holy See (Vatican City State)', 'VA'),
        new Menu('Iran, Islamic Republic Of', 'IR'),
        new Menu('Iraq', 'IQ'),
        new Menu('Isle Of Man', 'IM'),
        new Menu('Jersey', 'JE'),
        new Menu('Kiribati', 'KI'),
        new Menu('Korea, Democratic PeopleS Republic Of', 'KP'),
        new Menu('Liberia', 'LR'),
        new Menu('Libyan Arab Jamahiriya', 'LY'),
        new Menu('Mayotte', 'YT'),
        new Menu('Montenegro', 'ME'),
        new Menu('Myanmar', 'MM'),
        new Menu('Nauru', 'NR'),
        new Menu('Niue', 'NU'),
        new Menu('Norfolk Island', 'NF'),
        new Menu('Northern Mariana Islands', 'MP'),
        new Menu('Palestinian Territory, Occupied', 'PS'),
        new Menu('Pitcairn', 'PN'),
        new Menu('Saint Barthelemy', 'BL'),
        new Menu('Saint Helena', 'SH'),
        new Menu('Saint Kitts And Nevis', 'KN'),
        new Menu('Saint Lucia', 'LC'),
        new Menu('Saint Martin', 'MF'),
        new Menu('Saint Pierre And Miquelon', 'PM'),
        new Menu('Saint Vincent And The Grenadines', 'VC'),
        new Menu('Samoa', 'WS'),
        new Menu('Sao Tome And Principe', 'ST'),
        new Menu('Serbia', 'RS'),
        new Menu('Solomon Islands', 'SB'),
        new Menu('South Georgia And The South Sandwich Islands', 'GS'),
        new Menu('Sudan', 'SD'),
        new Menu('Svalbard And Jan Mayen', 'SJ'),
        new Menu('Swaziland', 'SZ'),
        new Menu('Tajikistan', 'TJ'),
        new Menu('Timor-Leste', 'TL'),
        new Menu('Tokelau', 'TK'),
        new Menu('Tonga', 'TO'),
        new Menu('Tuvalu', 'TV'),
        new Menu('United States Minor Outlying Islands', 'UM'),
        new Menu('Virgin Islands, British', 'VG'),
        new Menu('Western Sahara', 'EH')*/
     ];
    constructor(){}
}