import { Menu } from './menu';

export class States {
    public states = [
        new Menu('Alabama', 'AL'),
        new Menu('Alaska', 'AK'),
        new Menu('Arizona', 'AZ'),
        new Menu('Arkansas', 'AR'),
        new Menu('California', 'CA'),
        new Menu('Colorado', 'CO'),
        new Menu('Connecticut', 'CT'),
        new Menu('Delaware', 'DE'),
        new Menu('District of Columbia', 'DC'),
        new Menu('Florida', 'FL'),
        new Menu('Georgia', 'GA'),
        new Menu('Hawaii', 'HI'),
        new Menu('Idaho', 'ID'),
        new Menu('Illinois', 'IL'),
        new Menu('Indiana', 'IN'),
        new Menu('Iowa', 'IA'),
        new Menu('Kansas', 'KS'),
        new Menu('Kentucky', 'KY'),
        new Menu('Louisiana', 'LA'),
        new Menu('Maine', 'ME'),
        new Menu('Maryland', 'MD'),
        new Menu('Massachusetts', 'MA'),
        new Menu('Michigan', 'MI'),
        new Menu('Minnesota', 'MN'),
        new Menu('Mississippi', 'MS'),
        new Menu('Missouri', 'MO'),
        new Menu('Montana', 'MT'),
        new Menu('Nebraska', 'NE'),
        new Menu('Nevada', 'NV'),
        new Menu('New Hampshire', 'NH'),
        new Menu('New Jersey', 'NJ'),
        new Menu('New Mexico', 'NM'),
        new Menu('New York', 'NY'),
        new Menu('North Carolina', 'NC'),
        new Menu('North Dakota', 'ND'),
        new Menu('Ohio', 'OH'),
        new Menu('Oklahoma', 'OK'),
        new Menu('Oregon', 'OR'),
        new Menu('Pennsylvania', 'PA'),
        new Menu('Rhode Island', 'RI'),
        new Menu('South Carolina', 'SC'),
        new Menu('South Dakota', 'SD'),
        new Menu('Tennessee', 'TN'),
        new Menu('Texas', 'TX'),
        new Menu('Utah', 'UT'),
        new Menu('Vermont', 'VT'),
        new Menu('Virginia', 'VA'),
        new Menu('Washington', 'WA'),
        new Menu('West Virginia', 'WV'),
        new Menu('Wisconsin', 'WI'),
        new Menu('Wyoming', 'WY')
     ];
    constructor(){}
}